---

- name: Dump script ARC 
  hosts: "{{ servers }}"
  gather_facts: false
  tasks:
  - name: Run Dump_ARC
    ansible.builtin.shell: /backup/dump/dumpARC.sh
    args:
      executable: /bin/bash
      chdir: /backup/dump/
