---

- name: Dump db sql server 
  hosts: "{{ servers }}"
  gather_facts: false
  tasks:
    - name: Create striped full database backup in default dir
  lowlydba.sqlserver.backup:
    sql_instance: sql-01.myco.io
    database: LowlyDB
    type: full
    file_count: 8
