---

- name: backup db sql server 
  hosts: "{{ servers }}"
  gather_facts: false
  tasks:
  lowlydba.sqlserver.backup:
    sql_instance: MSSQLSERVER02
    sql_username: sa
    sql_password: Password!
    database: master
    type: full
    file_count: 8
    path: C:\SQL2022\Evaluation_ITA\bk
