---

- name: Dump script paas 
  hosts: "{{ servers }}"
  gather_facts: false
  tasks:
  - name: Run Dump_Paas
    ansible.builtin.shell: /backup/dump/dumpPaaS.sh
    args:
      executable: /bin/bash
      chdir: /backup/dump/
