---

- name: Start dedalus2 services
  hosts: "{{ servers }}"
  gather_facts: false
  tasks:
  - name: Start JamioDed2
    win_service:
      name: JamioDed2
      state: started
  - name: Start JamioEngineDed2
    win_service:
      name: JamioEngineDed2
      state: started
