---

- name: Stop desio1 services
  hosts: "{{ servers }}"
  gather_facts: false
  tasks:
  - name: Stop JamioDes1
    win_service:
      name: JamioDes1
      state: stopped
  - name: Stop JamioEngineDes1
    win_service:
      name: JamioEngineDes1
      state: stopped
