---

- name: Search Windows updates without installing them
  hosts: win_servers
  gather_facts: false
  tasks:
  - name: Search Windows Updates
    win_updates:
      state: searched
    register: result
  
