---

- name: Search Windows updates without installing them
  hosts: jamiotest
  gather_facts: false
  tasks:
  - name: Search Windows Updates
    win_updates:
      state: searched
    register: result
  - debug: var=result
